#!/usr/bin/env python3
"""Patch 26.09.2026: update_sentiment.py laeuft im Nightly nur noch woechentlich.

Warum: Kostenbremse (Entscheidung Paul). Google Places + Gemini fuer 27 Marken
liefen taeglich; der woechentliche Montagslauf des Preis-Workflows reicht.
Idempotent ueber die Signatur '_nur_woechentlich_ueberspringen' im NEUEN Text.
"""
import base64, sys
PFAD = "scripts/update_sentiment.py"
SIGNATUR = "def _nur_woechentlich_ueberspringen():"
PAARE = [("ZGVmIG1haW4oKToKICAgIHRvZGF5ID0gZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0Yykuc3RyZnRpbWUoIiVZLSVtLSVkIikK", "ZGVmIF9udXJfd29lY2hlbnRsaWNoX3VlYmVyc3ByaW5nZW4oKToKICAgICIiIktvc3RlbmJyZW1zZSAoMjYuMDkuMjAyNiwgRW50c2NoZWlkdW5nIFBhdWwpOiB3b2VjaGVudGxpY2ggc3RhdHQgdGFlZ2xpY2guCgogICAgR29vZ2xlIFBsYWNlcyB1bmQgR2VtaW5pIGxpZWZlbiBoaWVyIGZ1ZXIgMjcgTWFya2VuIEpFREVOIFRhZy4gRGllCiAgICBTaWNodGJhcmtlaXQgd2lyZCBhYmVyIG51ciB3b2VjaGVudGxpY2ggZ2VtZXNzZW4gLSB0YWVnbGljaGUgQmV3ZXJ0dW5ncy0KICAgIEVyZWlnbmlzc2UgYnJpbmdlbiBkZXIgQXVzd2VydHVuZyBrYXVtIGV0d2FzIHVuZCBrb3N0ZW4gMzB4IGltIE1vbmF0LgoKICAgIERlciB3b2VjaGVudGxpY2hlIExhdWYgaXN0IGRlciBNb250YWdzLUxhdWYgdm9uICJXZWVrbHkgQ2hlY2syNCBQcmljZXMgJgogICAgUmV2aWV3cyIgKGRlciBydWZ0IGRpZXNlcyBTa3JpcHQgb2huZWhpbiBpbSBXb2NoZW5sYXVmIGF1ZikuIERlciB0YWVnbGljaGUKICAgIE5pZ2h0bHkgdWViZXJzcHJpbmd0IGRlc2hhbGIsIEFVU1NFUjoKICAgICAgLSBlciB3dXJkZSB2b24gSGFuZCBnZXN0YXJ0ZXQgKHdvcmtmbG93X2Rpc3BhdGNoKSwgb2RlcgogICAgICAtIGRpZSBsZXR6dGUgQXVzd2VydHVuZyAoYXNfb2YpIGlzdCBhZWx0ZXIgYWxzIDcgVGFnZSAtIFNpY2hlcmhlaXRzbmV0eiwKICAgICAgICBmYWxscyBkZXIgTW9udGFnc2xhdWYgYXVzZmllbC4gRGVyIFBpcGVsaW5lLVdhZWNodGVyIG1lbGRldCBlcnN0IGFiIDkuCiAgICBFcnp3aW5nZW46IFNFTlRJTUVOVF9FUlpXSU5HRU49MQoKICAgIEFDSFRVTkcgZnVlciBkaWUgQXVzd2VydHVuZzogQWIgZGllc2VtIFRhZyBlbnRzdGVoZW4gcmV2aWV3X2NoYW5nZSAvCiAgICByZXZpZXdfdm9sdW1lLUVyZWlnbmlzc2Ugd29lY2hlbnRsaWNoIChrdW11bGllcnQpIHN0YXR0IHRhZWdsaWNoLiBEYXMgaXN0CiAgICBlaW4gUmVnaW1ld2VjaHNlbCBpbiBkZXIgRXJlaWduaXN6YWhsLCBrZWluIE1lc3NicnVjaCBkZXIgU2ljaHRiYXJrZWl0LgogICAgIiIiCiAgICBpZiBvcy5lbnZpcm9uLmdldCgiU0VOVElNRU5UX0VSWldJTkdFTiIpID09ICIxIjoKICAgICAgICByZXR1cm4gRmFsc2UKICAgIGlmIG9zLmVudmlyb24uZ2V0KCJHSVRIVUJfRVZFTlRfTkFNRSIpICE9ICJzY2hlZHVsZSI6CiAgICAgICAgcmV0dXJuIEZhbHNlCiAgICBpZiAiTmlnaHRseSIgbm90IGluIG9zLmVudmlyb24uZ2V0KCJHSVRIVUJfV09SS0ZMT1ciLCAiIik6CiAgICAgICAgcmV0dXJuIEZhbHNlCiAgICB0cnk6CiAgICAgICAgcGZhZCA9IG9zLnBhdGguam9pbihvcy5wYXRoLmRpcm5hbWUob3MucGF0aC5hYnNwYXRoKF9fZmlsZV9fKSksICIuLiIsICJkYXRhIiwgInNlbnRpbWVudF9kYXNoYm9hcmQuanNvbiIpCiAgICAgICAgd2l0aCBvcGVuKHBmYWQsICJyIiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICAgICAgc3RhbmQgPSBqc29uLmxvYWQoZikuZ2V0KCJhc19vZiIsICIiKQogICAgICAgIGFsdGVyID0gKGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLmRhdGUoKSAtIGRhdGV0aW1lLnN0cnB0aW1lKHN0YW5kLCAiJVktJW0tJWQiKS5kYXRlKCkpLmRheXMKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcmV0dXJuIEZhbHNlICAjIGtlaW4gbGVzYmFyZXIgU3RhbmQgLT4gbGllYmVyIGxhdWZlbgogICAgaWYgYWx0ZXIgPiA3OgogICAgICAgIHByaW50KCJTaWNoZXJoZWl0c25ldHo6IFN0aW1tdW5nc2RhdGVuIHNpbmQgJWQgVGFnZSBhbHQgLSBMYXVmIHdpcmQgYXVzZ2VmdWVocnQuIiAlIGFsdGVyKQogICAgICAgIHJldHVybiBGYWxzZQogICAgcHJpbnQoIktvc3RlbmJyZW1zZTogU3RpbW11bmdzLUF1c3dlcnR1bmcgbGFldWZ0IHdvZWNoZW50bGljaCAoTW9udGFnLCBQcmVpcy1Xb3JrZmxvdykuICIKICAgICAgICAgICJMZXR6dGUgQXVzd2VydHVuZyB2b3IgJWQgVGFnZW4gLSBOaWdodGx5IHVlYmVyc3ByaW5ndC4iICUgYWx0ZXIpCiAgICByZXR1cm4gVHJ1ZQoKCmRlZiBtYWluKCk6CiAgICBpZiBfbnVyX3dvZWNoZW50bGljaF91ZWJlcnNwcmluZ2VuKCk6CiAgICAgICAgcmV0dXJuCiAgICB0b2RheSA9IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnN0cmZ0aW1lKCIlWS0lbS0lZCIpCg==")]

s = open(PFAD, "r", encoding="utf-8").read()
if SIGNATUR in s:
    print("SKIP: bereits angewendet"); sys.exit(0)
for a64, n64 in PAARE:
    a = base64.b64decode(a64).decode("utf-8"); n = base64.b64decode(n64).decode("utf-8")
    anzahl = s.count(a)
    if anzahl != 1:
        print(f"ABBRUCH: Ankertext kommt {anzahl}x vor statt 1x - nichts geaendert."); sys.exit(1)
    s = s.replace(a, n)
open(PFAD, "w", encoding="utf-8").write(s)
print("OK: Kostenbremse in update_sentiment.py eingebaut")
